\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Coordinated\_Ordering},
  pdfauthor={GroupB},
  pdfborder={0 0 0},
  breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-2}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\title{Coordinated\_Ordering}
\author{GroupB}
\date{22/07/2020}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(kableExtra)}
\KeywordTok{library}\NormalTok{(knitr)}
\end{Highlighting}
\end{Shaded}

\hypertarget{data-preparation}{%
\section{Data preparation}\label{data-preparation}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(readxl)}

\NormalTok{product_data <-}\StringTok{ }\KeywordTok{read_excel}\NormalTok{(}\StringTok{"Data_ordering.xlsx"}\NormalTok{,}\DataTypeTok{sheet =} \StringTok{"product data"}\NormalTok{)}
\NormalTok{box_data <-}\StringTok{ }\KeywordTok{read_excel}\NormalTok{(}\StringTok{"Data_ordering.xlsx"}\NormalTok{,}\DataTypeTok{sheet =} \StringTok{"box data"}\NormalTok{)}
\CommentTok{#rack data}
\NormalTok{Total_racks=}\DecValTok{8}
\NormalTok{levels_per_rack=}\DecValTok{4}
\NormalTok{rack_length=}\StringTok{ }\DecValTok{6000}
\NormalTok{rack_width=}\DecValTok{1750}
\NormalTok{rack_height=}\DecValTok{300}
\end{Highlighting}
\end{Shaded}

\hypertarget{convert-to-boxes}{%
\subsection{Convert to Boxes}\label{convert-to-boxes}}

Convert demand \(d_i\), quantity \(q_i\) and unit price \(p_i\) all from
part \(i\) to box \(bc_i\) which is the capacity of a box for part
\(i\).

Demand for box with part \(i\) . \[y_i=\frac {d_i}{bc_i} \]

Price for box with material \(i\) .\[pr_i= b_i \cdot p_i\]

\(y_i = demand\_per\_year \\ ,\) \(pr_i = box\_cost\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{product_data}\OperatorTok{$}\NormalTok{demand_per_year=}\StringTok{ }\KeywordTok{ceiling}\NormalTok{((product_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{demand per day}\StringTok{`} \OperatorTok{*}\DecValTok{262}\NormalTok{)}\OperatorTok{/}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{pieces/box}\StringTok{`}\NormalTok{) }

\NormalTok{product_data}\OperatorTok{$}\NormalTok{box_cost=}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{pieces/box}\StringTok{`} \OperatorTok{*}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\NormalTok{price}

\NormalTok{product_data}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 62 x 7
##    `material ID` `demand per day` `box ID` `pieces/box` price demand_per_year
##    <chr>                    <dbl>    <dbl>        <dbl> <dbl>           <dbl>
##  1 7305667+74                  12  6203060           45  1.51              70
##  2 7305669+77                  30  6203059           15  7.62             524
##  3 7305670+77                  30  6203059           15  1.62             524
##  4 7305673+76                  30  6203059           16  1.51             492
##  5 7305674+76                  30  6203059           16  1.51             492
##  6 7305817+74                  60  6203060           16  4.55             983
##  7 7305819+79                  30  6203059            6 11.1             1310
##  8 7305820+79                  30  6203059            6  2.86            1310
##  9 7305823+73                  30  6203059           30  4.05             262
## 10 7305824+73                  30  6203059           30  2.56             262
## # ... with 52 more rows, and 1 more variable: box_cost <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{product_data <-}\StringTok{ }\KeywordTok{merge}\NormalTok{(product_data, box_data[,}\KeywordTok{c}\NormalTok{(}\StringTok{"box ID"}\NormalTok{, }\StringTok{"ordering cost (€)"}\NormalTok{)], }\DataTypeTok{by =} \StringTok{"box ID"}\NormalTok{)}

\KeywordTok{colnames}\NormalTok{(product_data)[}\DecValTok{8}\NormalTok{] <-}\StringTok{ "ordering_cost"}
\end{Highlighting}
\end{Shaded}

\hypertarget{separate-ordering-so}{%
\section{Separate Ordering (SO)}\label{separate-ordering-so}}

\(c_i^{or}=\) ordering cost for part \(i ,\space\)

\(c_i^{sh}=\) stock holding cost rate based on unit price \(p_i\) and
interest rate \(h, \qquad\). \(c_i^{sh}=p_i \cdot h\)

calculate EOQ for each part i:
\[ q_i^* = \sqrt \frac {2 \cdot y_i \cdot (c_i^{or}+c^{-or})} {pr_i \cdot h}\]

\hypertarget{eoq-modelling}{%
\subsection{EOQ modelling}\label{eoq-modelling}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#dei= demand_per_year, cori= ordering cost for box i}
\CommentTok{#cord= ordering cost, pri= box cost, h= interest rate}

\CommentTok{# directly vectorized}
\NormalTok{so_eoq_fun <-}\StringTok{ }\KeywordTok{Vectorize}\NormalTok{(}\ControlFlowTok{function}\NormalTok{(dei,cori,cord,pri,h)\{}
\NormalTok{  eoq<-}\StringTok{ }\KeywordTok{sqrt}\NormalTok{((}\DecValTok{2}\OperatorTok{*}\NormalTok{dei}\OperatorTok{*}\NormalTok{(cori}\OperatorTok{+}\NormalTok{cord))}\OperatorTok{/}\NormalTok{(pri}\OperatorTok{*}\NormalTok{h))}
  \KeywordTok{return}\NormalTok{(eoq)}
\NormalTok{\})}

\CommentTok{# maximum EOQ provided there is no coordination of ordering cycles (i.e., cord are not shared among parallely ordered items)}
\NormalTok{vec_so_eoq_fun.max <-}\StringTok{ }\KeywordTok{so_eoq_fun}\NormalTok{(}\DataTypeTok{dei =}\NormalTok{ product_data}\OperatorTok{$}\NormalTok{demand_per_year,}\DataTypeTok{cori=}\NormalTok{product_data}\OperatorTok{$}\NormalTok{ordering_cost,}\DataTypeTok{cord=}\DecValTok{1500}\NormalTok{,}\DataTypeTok{pri=}\NormalTok{product_data}\OperatorTok{$}\NormalTok{box_cost,}\DataTypeTok{h=}\FloatTok{0.10}\NormalTok{)}
\CommentTok{# minimum EOQ disregarding common ordering cost cord}
\NormalTok{vec_so_eoq_fun.min <-}\StringTok{ }\KeywordTok{so_eoq_fun}\NormalTok{(}\DataTypeTok{dei =}\NormalTok{ product_data}\OperatorTok{$}\NormalTok{demand_per_year,}\DataTypeTok{cori=}\NormalTok{product_data}\OperatorTok{$}\NormalTok{ordering_cost,}\DataTypeTok{cord=}\DecValTok{0}\NormalTok{,}\DataTypeTok{pri=}\NormalTok{product_data}\OperatorTok{$}\NormalTok{box_cost,}\DataTypeTok{h=}\FloatTok{0.10}\NormalTok{)}

\NormalTok{product_data}\OperatorTok{$}\NormalTok{eoq.min <-}\StringTok{ }\KeywordTok{round}\NormalTok{(vec_so_eoq_fun.min)}
\NormalTok{product_data}\OperatorTok{$}\NormalTok{eoq.max <-}\StringTok{ }\KeywordTok{round}\NormalTok{(vec_so_eoq_fun.max)}
\end{Highlighting}
\end{Shaded}

\hypertarget{lane-occupation}{%
\subsection{Lane Occupation}\label{lane-occupation}}

\(b_i=\) sorting column lenght or width.This determines the rack width

\(b_i^{-1}=\)if sorted by length then the value is width and vice versa,
used for rack lenght.

Add \(b_i\) and \(b_i^{-1}\) to product\_data table

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# constraints #####################################}
\CommentTok{# this can be formulated more elegantly, but it works and that suffices}
\NormalTok{b_sorting <-}\StringTok{ }\KeywordTok{double}\NormalTok{(}\KeywordTok{length}\NormalTok{(product_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{box ID}\StringTok{`}\NormalTok{)) }
\NormalTok{b_not_sorting <-}\KeywordTok{double}\NormalTok{(}\KeywordTok{length}\NormalTok{(product_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{box ID}\StringTok{`}\NormalTok{))}

\ControlFlowTok{for}\NormalTok{(j }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\StringTok{ }\KeywordTok{length}\NormalTok{(box_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{box ID}\StringTok{`}\NormalTok{))\{}
  \ControlFlowTok{for}\NormalTok{ (k }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{length}\NormalTok{(product_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{box ID}\StringTok{`}\NormalTok{)) \{}
    \ControlFlowTok{if}\NormalTok{(box_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{box ID}\StringTok{`}\NormalTok{[j]}\OperatorTok{==}\NormalTok{product_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{box ID}\StringTok{`}\NormalTok{[k])\{}
      
      \ControlFlowTok{if}\NormalTok{(box_data}\OperatorTok{$}\NormalTok{sorting[j]}\OperatorTok{==}\StringTok{"width"}\NormalTok{)\{}
\NormalTok{        b_sorting[k] <-}\StringTok{ }\NormalTok{box_data}\OperatorTok{$}\NormalTok{width[j]}
\NormalTok{        b_not_sorting[k]<-}\StringTok{ }\NormalTok{box_data}\OperatorTok{$}\NormalTok{length[j]}
        
\NormalTok{      \}}\ControlFlowTok{else}\NormalTok{\{}
\NormalTok{        b_sorting[k] <-}\StringTok{ }\NormalTok{box_data}\OperatorTok{$}\NormalTok{length[j]}
\NormalTok{        b_not_sorting[k]<-}\StringTok{ }\NormalTok{box_data}\OperatorTok{$}\NormalTok{width[j]}
\NormalTok{      \}}
\NormalTok{    \}}
\NormalTok{  \}}
  
\NormalTok{\}}

\NormalTok{product_data}\OperatorTok{$}\NormalTok{b_sorting <-}\StringTok{ }\NormalTok{b_sorting }
\NormalTok{product_data}\OperatorTok{$}\NormalTok{b_not_sorting <-}\StringTok{ }\NormalTok{b_not_sorting}

\NormalTok{lane.min <-}\StringTok{ }\KeywordTok{ceiling}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.min }\OperatorTok{*}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\NormalTok{b_not_sorting }\OperatorTok{/}\StringTok{ }\NormalTok{rack_length)}
\NormalTok{lane.max <-}\StringTok{ }\KeywordTok{ceiling}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.max }\OperatorTok{*}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\NormalTok{b_not_sorting }\OperatorTok{/}\StringTok{ }\NormalTok{rack_length)}

\CommentTok{# total rack width }

\NormalTok{rack_total_width <-}\StringTok{ }\NormalTok{rack_width }\OperatorTok{*}\StringTok{ }\DecValTok{4} \OperatorTok{*}\StringTok{ }\DecValTok{8}

\CommentTok{# overflow in mm}
\KeywordTok{sum}\NormalTok{(lane.min}\OperatorTok{*}\NormalTok{product_data}\OperatorTok{$}\NormalTok{b_sorting) }\OperatorTok{-}\StringTok{ }\NormalTok{rack_total_width}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 213894
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(lane.max}\OperatorTok{*}\NormalTok{product_data}\OperatorTok{$}\NormalTok{b_sorting) }\OperatorTok{-}\StringTok{ }\NormalTok{rack_total_width}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1168292
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# relative overflow in %}
\NormalTok{(}\KeywordTok{sum}\NormalTok{(lane.min}\OperatorTok{*}\NormalTok{product_data}\OperatorTok{$}\NormalTok{b_sorting) }\OperatorTok{-}\StringTok{ }\NormalTok{rack_total_width)}\OperatorTok{/}\NormalTok{rack_total_width}\OperatorTok{*}\DecValTok{100}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 381.9536
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\KeywordTok{sum}\NormalTok{(lane.max}\OperatorTok{*}\NormalTok{product_data}\OperatorTok{$}\NormalTok{b_sorting) }\OperatorTok{-}\StringTok{ }\NormalTok{rack_total_width)}\OperatorTok{/}\NormalTok{rack_total_width}\OperatorTok{*}\DecValTok{100}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2086.236
\end{verbatim}

E.g Using box\_ID 6203060, sorted by length \(b_i=396\),
\(b_i^{-1}=297\) Also for material ID 7305667+74 with \(q_i=214\)
therefore, \(rack_{length}=6000 \\\) 1. Number of boxes in a lane:
\[n_i=\frac {rack_{length}}{b_i^{-1}}=\frac {6000}{297}=20.20=20boxes\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  How many lanes part \(i\) will occupy if you order some number of
  boxes
  \[lane_i=\frac {q_i}{n_i}\\lane_i=q_i \cdot \frac {b_i^{-1}}{rack_{length}}=214 \cdot \frac {297}{6000}=10.593= 11 \space lanes \]
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lane <-}\StringTok{ }\KeywordTok{ceiling}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq }\OperatorTok{*}\StringTok{ }\NormalTok{(product_data}\OperatorTok{$}\NormalTok{b_not_sorting}\OperatorTok{/}\NormalTok{rack_length))}
\NormalTok{lane}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## numeric(0)
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\Alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Do we meet the capacity contraint?
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Total number of lanes constraints
\end{enumerate}

Collapsing Rack 4 levels in a rack and joining the 8 racks to become 1
level.

Total rack width available:

\[rack_{total_{Width}}=(rack_{width} \times 4 \times 8)\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rack_total_width <-rack_width }\OperatorTok{*}\StringTok{ }\DecValTok{4} \OperatorTok{*}\StringTok{ }\DecValTok{8}
\NormalTok{rack_total_width }\CommentTok{#56000}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 56000
\end{verbatim}

Please note the coefficients are are different for every ith item except
racklength which is the same for all items.Also the left and right hand
side of the equation need to be in mm.
\[\sum_{i=1}^{n=62}lane_i \cdot b_i\le rack_{Total_{width}} \\ \sum_{i=1}^{n=62} q_i \cdot \frac {b_i^{-1} \cdot b_i}{rack_{length}} \le rack_{Total_{width}} \quad \quad (1)\]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#get the with of the lanes in mm}
\NormalTok{rack_width_occupied=}\KeywordTok{sum}\NormalTok{(}\KeywordTok{sum}\NormalTok{(lane}\OperatorTok{*}\NormalTok{product_data}\OperatorTok{$}\NormalTok{b_sorting))}
\NormalTok{rack_width_occupied}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{(rack_width_occupied }\OperatorTok{<=}\StringTok{ }\NormalTok{rack_total_width)\{}
  \KeywordTok{print}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(}\StringTok{"Capacity constraint fulfilled: "}\NormalTok{, rack_width_occupied, }\StringTok{"<="}\NormalTok{,rack_total_width))}
 
\NormalTok{\}}\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{  violated <-}\StringTok{ }\NormalTok{rack_width_occupied }\OperatorTok{-}\StringTok{ }\NormalTok{rack_total_width}
  \KeywordTok{print}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(}\StringTok{"Capacity constraint violated by: "}\NormalTok{,violated ))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Capacity constraint fulfilled: 0<=56000"
\end{verbatim}

As seen above contraint was voilated by \(1387664 mm\), this means that
we ordered too much, therefore we need to optimize \(q_i\)

Using our example to get number of the total width i.e (summation of
lanes) in \(mm\): Summation of lanes can simply be:
\[lanes_i \cdot b_i= 10.593 \cdot 396=4194.828\] Using equation (1) to
prove this concept.

\[214 \cdot \frac {396 \cdot 297}{6000}=4194.828 \\ b_i= \frac {4194.828}{10.593}=396\]

\begin{enumerate}
\def\labelenumi{(\Alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Adjust Q by reducing it:
\end{enumerate}

\(\frac {y_i}{q_i}=\) no of orders for part \(i \\\) \(\frac {q_i}{2}=\)
average inventory for part \(i\)

\hypertarget{constrained-eoq-optimization}{%
\subsection{Constrained EOQ
optimization}\label{constrained-eoq-optimization}}

\[ min \rightarrow (\sum_{i=1}^{n=62}c^{-or} + \sum_{i=1}^{n=62} \frac {y_i}{q_i} \cdot c_i^{or}) + (h \cdot \sum_{i=1}^{n=62} \frac {q_i}{2}\cdot pr_i ) \]
Subject to:
\[\sum_{i=1}^{n=62} q_i \cdot \frac {b_i^{-1} \cdot b_i}{rack_{length}} \le rack_{Total_{width}} \]

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ROI)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ROI: R Optimization Infrastructure
\end{verbatim}

\begin{verbatim}
## Registered solver plugins: nlminb, alabama, glpk, quadprog, symphony.
\end{verbatim}

\begin{verbatim}
## Default solver: auto.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ROI.plugin.alabama)}

\NormalTok{n <-}\StringTok{ }\KeywordTok{length}\NormalTok{(product_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{material ID}\StringTok{`}\NormalTok{) }\CommentTok{#number of materials}
\NormalTok{cori <-}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\NormalTok{ordering_cost   }\CommentTok{#ordering cost for each items}
\NormalTok{cord <-}\StringTok{  }\DecValTok{1500}    \CommentTok{#ordering cost whenever there is an order}
\NormalTok{dei <-}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\NormalTok{demand_per_year}
\NormalTok{h<-}\FloatTok{0.10}
\NormalTok{box_cost <-}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\NormalTok{box_cost }\CommentTok{#pri}

\CommentTok{# objective function --> I dropped the 1500*62 as it is not decision relevant}
\NormalTok{obj.fun <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(q, }\DataTypeTok{d=}\NormalTok{ dei, }\DataTypeTok{c.or =}\NormalTok{ cori, }\DataTypeTok{c.h =}\NormalTok{ h}\OperatorTok{*}\NormalTok{box_cost  ) (}\KeywordTok{sum}\NormalTok{((dei}\OperatorTok{/}\NormalTok{q)}\OperatorTok{*}\NormalTok{c.or)}\OperatorTok{+}\StringTok{ }\KeywordTok{sum}\NormalTok{(c.h}\OperatorTok{*}\NormalTok{(q}\OperatorTok{/}\DecValTok{2}\NormalTok{)))}
\CommentTok{# benchmarks}
\KeywordTok{obj.fun}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.max)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 79279.71
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{obj.fun}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.min)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 31501.53
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# constraint function --> also contains the ceiling of lanes and a sum was missing}
\NormalTok{const.fun <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(q, }\DataTypeTok{bns =}\NormalTok{ product_data}\OperatorTok{$}\NormalTok{b_not_sorting, }\DataTypeTok{bs =}\NormalTok{ product_data}\OperatorTok{$}\NormalTok{b_sorting, }\DataTypeTok{rl =}\NormalTok{ rack_length) \{}
  \KeywordTok{sum}\NormalTok{(bs }\OperatorTok{*}\StringTok{ }\KeywordTok{ceiling}\NormalTok{( bns }\OperatorTok{*}\StringTok{ }\NormalTok{q }\OperatorTok{/}\StringTok{ }\NormalTok{rl))}
\NormalTok{  \}}

\KeywordTok{const.fun}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.max)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1224292
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{const.fun}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.min)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 269894
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# try to figure out a freasible starting solution}
\KeywordTok{const.fun}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.min}\OperatorTok{/}\DecValTok{10}\NormalTok{) }\OperatorTok{-}\StringTok{  }\NormalTok{rack_total_width}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -15186
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{qopt <-}\StringTok{ }\KeywordTok{OP}\NormalTok{(}
  \DataTypeTok{objective =} \KeywordTok{F_objective}\NormalTok{(}\DataTypeTok{F=}\NormalTok{obj.fun ,}\DataTypeTok{n=}\NormalTok{n),}
  \DataTypeTok{types =} \KeywordTok{rep}\NormalTok{(}\StringTok{"C"}\NormalTok{,n),}
  \DataTypeTok{bounds =} \KeywordTok{V_bound}\NormalTok{(}\DataTypeTok{ub=}\NormalTok{ product_data}\OperatorTok{$}\NormalTok{eoq.min , }\DataTypeTok{lb=} \KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, n)),}
  \DataTypeTok{constraints =} \KeywordTok{F_constraint}\NormalTok{(}\DataTypeTok{F=}\NormalTok{const.fun,}
                             \DataTypeTok{dir=}\StringTok{"<="}\NormalTok{,}
                             \DataTypeTok{rhs =}\NormalTok{ rack_total_width)}
\NormalTok{)}

\CommentTok{#This shows that minimum EOQ is too big and therefore will not meet the rack space constraint.}
\KeywordTok{const.fun}\NormalTok{(}\KeywordTok{min}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.max))}\CommentTok{#366272}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 313556
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{const.fun}\NormalTok{(}\KeywordTok{min}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.max)}\OperatorTok{/}\DecValTok{8}\NormalTok{)}\CommentTok{# 61428  still > 56000}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 52716
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{const.fun}\NormalTok{(}\KeywordTok{min}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.max)}\OperatorTok{/}\FloatTok{8.7}\NormalTok{)}\CommentTok{#52716 < 56000}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 52716
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{const.fun}\NormalTok{(}\KeywordTok{round}\NormalTok{(}\KeywordTok{min}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.max)}\OperatorTok{/}\DecValTok{10}\NormalTok{))}\CommentTok{# 52716 < 56000}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 33098
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{(}\KeywordTok{min}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.max)}\OperatorTok{/}\DecValTok{10}\NormalTok{) }\CommentTok{#17.3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{copt_sol <-}\StringTok{ }\KeywordTok{ROI_solve}\NormalTok{(qopt, }\DataTypeTok{start =} \KeywordTok{rep}\NormalTok{(}\KeywordTok{min}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{eoq.max)}\OperatorTok{/}\DecValTok{10}\NormalTok{,n), }\DataTypeTok{solver =} \StringTok{"alabama"}\NormalTok{ )}
\CommentTok{# always check whether the algorithm converged}
\NormalTok{copt_sol}\CommentTok{# The objective value is: 1.313873e+05}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Optimal solution found.
## The objective value is: 1.016259e+05
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# solution}
\NormalTok{copt_sol}\OperatorTok{$}\NormalTok{solution }\CommentTok{#vector of optimal Quantity that meets the space constraints and minimizes the Obj function.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 22.46022 17.99289 20.19523 20.19523 22.73522 18.40410 21.37358 22.58662
##  [9] 20.43468 19.96846 21.74025 18.07728 20.71279 20.84992 17.73845 22.30781
## [17] 22.72686 16.69259 22.50153 21.38765 16.48757 22.72682 22.12405 20.95047
## [25] 20.91820 20.91967 20.44923 19.58981 22.38354 19.57130 19.59465 21.69385
## [33] 22.02758 21.01991 20.03569 18.08505 22.75130 22.75752 20.93491 22.91532
## [41] 18.25628 19.42262 18.32606 19.82644 19.98579 22.91450 19.39880 18.61224
## [49] 16.64720 23.03742 19.64823 20.56920 17.78781 16.49775 23.04797 17.73769
## [57] 19.71384 22.42010 20.90386 20.20202 17.35202 17.68072
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{(copt_sol}\OperatorTok{$}\NormalTok{solution)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 22 18 20 20 23 18 21 23 20 20 22 18 21 21 18 22 23 17 23 21 16 23 22 21 21
## [26] 21 20 20 22 20 20 22 22 21 20 18 23 23 21 23 18 19 18 20 20 23 19 19 17 23
## [51] 20 21 18 16 23 18 20 22 21 20 17 18
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{copt_sol}\OperatorTok{$}\NormalTok{objval }\CommentTok{#131387.3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 101625.9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#########################################}
\CommentTok{# Now you need to fine tune the results }
\CommentTok{# --> there are rounding issues -> exactly determining the lane configuration per shelf level}
\CommentTok{# --> idea to coping with the common ordering cost}

\KeywordTok{const.fun}\NormalTok{(copt_sol}\OperatorTok{$}\NormalTok{solution)}\CommentTok{#55884}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 55884
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{const.fun}\NormalTok{(}\KeywordTok{round}\NormalTok{(copt_sol}\OperatorTok{$}\NormalTok{solution))}\CommentTok{#55686}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 56480
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{obj.fun}\NormalTok{(copt_sol}\OperatorTok{$}\NormalTok{solution)}\CommentTok{#131387.3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 101625.9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{obj.fun}\NormalTok{(}\KeywordTok{round}\NormalTok{(copt_sol}\OperatorTok{$}\NormalTok{solution))}\CommentTok{#132096.3  rounded q values}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 101592.8
\end{verbatim}

\hypertarget{joint-ordering-jo}{%
\section{Joint Ordering (JO)}\label{joint-ordering-jo}}

Using Joint replenishment problem

Assumptions:

\begin{itemize}
\tightlist
\item
  One supplier with outbound storage.
\item
  \(i=\{1,...,n\}\) products
\item
  Demand rates: \(de_i\)
\item
  Stock\_holding cost rates: \(c_i^{sh}\)
\item
  Specific setup costs: \(c_i^{or}\)
\item
  General setup costs: \(c^{-or}\)
\item
  Cycle time of product \(i\): \(T_i\)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n <-}\StringTok{ }\KeywordTok{length}\NormalTok{(product_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{box ID}\StringTok{`}\NormalTok{)}
\NormalTok{c.or0 <-}\StringTok{ }\NormalTok{cord}
\NormalTok{c.or <-}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\NormalTok{ordering_cost}
\CommentTok{#H.vec <- 0.5 * dei * c.sh}
\CommentTok{# based on the previous definition, I think this should be the vector of holding cost multipliers}
\NormalTok{H.vec <-}\StringTok{ }\FloatTok{0.1} \OperatorTok{*}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\NormalTok{box_cost }\OperatorTok{*}\StringTok{ }\NormalTok{dei }\OperatorTok{*}\StringTok{ }\FloatTok{.05}
\end{Highlighting}
\end{Shaded}

\hypertarget{objective-function-with-no-capacity-constraint}{%
\subsection{Objective Function with no capacity
constraint}\label{objective-function-with-no-capacity-constraint}}

\begin{itemize}
\tightlist
\item
  \(B=\)basic cycle time
\item
  \(H_i=0.5 \cdot y_i \cdot c_i^{sh}\)
\item
  \(H_0=0\) Holding cost multiplier are \(H_0 \space and \space H_i\)
\item
  \[C(m_i B)=\sum_{i=0}^n (\frac {c_i^{or}}{m_i \cdot B}+H_i \cdot m_i \cdot B) == \frac {c_o^{or}}{B}+ \sum_{i=1}^n (\frac {c_i^{or}}{m_i \cdot B}+H_i \cdot m_i \cdot B)  \\ subject \space to: \quad \quad \quad \quad \quad \quad \quad \quad \quad  \\ m_i \ge m_0 \quad \forall i >0 \\m_i \in \mathbb N \qquad \forall i   \]
\end{itemize}

--\textgreater{} an important side note is that the JRP is basically a
quite standard EOQ problem which uses the substitution
\(T_i = \frac{q_i}{y_i}\), i.e., \(q_i = T_i \cdot y_i\). Then, you
substitute \(T_i = m_i \cdot B\) ans result in the JRP (adding the
common ordering cost).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{jrp.obj.fun <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(m , B, cor, Hvec, cor0) cor0}\OperatorTok{/}\NormalTok{B }\OperatorTok{+}\StringTok{ }\KeywordTok{sum}\NormalTok{(cor}\OperatorTok{/}\NormalTok{B}\OperatorTok{/}\NormalTok{m) }\OperatorTok{+}\StringTok{ }\KeywordTok{sum}\NormalTok{(Hvec}\OperatorTok{*}\NormalTok{B}\OperatorTok{*}\NormalTok{m)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \emph{Cycle Time}
\end{itemize}

we determine \(T_i=\sqrt (\frac {c_i^{or}}{H_i})\) and
\(T^C=\frac {\sum_{j=0}^{i´} c_j^{or}}{\sum_{j=0}^{i´}H_j}\)

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# calculate cycle times}
\NormalTok{T.vec <-}\StringTok{ }\KeywordTok{sqrt}\NormalTok{(c.or}\OperatorTok{/}\NormalTok{H.vec)}
\CommentTok{# order products}
\NormalTok{reo.id <-}\StringTok{ }\KeywordTok{order}\NormalTok{(T.vec)}
\NormalTok{T.vec <-}\StringTok{ }\NormalTok{T.vec[reo.id]}
\NormalTok{c.or <-}\StringTok{ }\NormalTok{c.or[reo.id]}
\NormalTok{H.vec <-}\StringTok{ }\NormalTok{H.vec[reo.id]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(kableExtra)}
\CommentTok{# calculate T^2 and cumu. cost shares}
\NormalTok{res.mat <-}\StringTok{ }\KeywordTok{t}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(c.or}\OperatorTok{/}\NormalTok{H.vec,(c.or0 }\OperatorTok{+}\StringTok{ }\KeywordTok{cumsum}\NormalTok{(c.or))}\OperatorTok{/}\KeywordTok{cumsum}\NormalTok{(H.vec)))}
\NormalTok{df <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(res.mat)}
\KeywordTok{colnames}\NormalTok{(df) <-}\StringTok{ }\NormalTok{reo.id }
\KeywordTok{rownames}\NormalTok{(df) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(  }\StringTok{"$T_i$"}\NormalTok{ ,}\StringTok{"$T^C$"}\NormalTok{  )}
\KeywordTok{kable}\NormalTok{(df,}\StringTok{"pandoc"}\NormalTok{, }\DataTypeTok{row.names =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr@{}}
\toprule
& 2 & 10 & 7 & 15 & 9 & 41 & 58 & 19 & 20 & 3 & 4 & 57 & 59 & 14 & 5 & 1
& 33 & 61 & 13 & 29 & 18 & 50 & 34 & 21 & 55 & 60 & 23 & 52 & 38 & 37 &
25 & 39 & 51 & 32 & 8 & 28 & 46 & 62 & 40 & 24 & 16 & 11 & 17 & 22 & 27
& 35 & 43 & 54 & 12 & 44 & 49 & 30 & 36 & 31 & 56 & 53 & 48 & 45 & 6 &
47 & 42 & 26\tabularnewline
\midrule
\endhead
\(T_i\) & 0.0532684 & 0.0841445 & 0.0849380 & 0.1828952 & 0.1932178 &
0.2096073 & 0.2596458 & 0.2671422 & 0.3015609 & 0.3254149 & 0.3254149 &
0.4118155 & 0.4509282 & 0.4767268 & 0.4841794 & 0.4927497 & 0.5026231 &
0.5162813 & 0.5181529 & 0.6432026 & 0.6692724 & 0.6793183 & 0.6877106 &
0.7117564 & 0.7217757 & 0.7595160 & 0.7951654 & 0.8481764 & 0.8876265 &
0.8959610 & 1.0077344 & 1.0198843 & 1.0307153 & 1.0370002 & 1.0461345 &
1.052546 & 1.1283676 & 1.1345035 & 1.1350841 & 1.1632134 & 1.2565577 &
1.2921438 & 1.3460400 & 1.3460400 & 1.5345514 & 1.791922 & 2.4852542 &
2.4858926 & 2.6120153 & 2.6342317 & 2.9807148 & 3.0598585 & 3.1535793 &
3.2456007 & 3.4211427 & 3.9068604 & 4.1638907 & 4.4769571 & 5.4852321 &
5.5704100 & 6.1893444 & 6.7276359\tabularnewline
\(T^C\) & 1.6513197 & 0.9438241 & 0.6784073 & 0.6040228 & 0.5615030 &
0.5266050 & 0.5130786 & 0.4951155 & 0.4833530 & 0.4785034 & 0.4739428 &
0.4723593 & 0.4718717 & 0.4720333 & 0.4723247 & 0.4727182 & 0.4735953 &
0.4746358 & 0.4755956 & 0.4791824 & 0.4830132 & 0.4854192 & 0.4892634 &
0.4932751 & 0.4957864 & 0.4985124 & 0.5031256 & 0.5062413 & 0.5111143 &
0.5159249 & 0.5216867 & 0.5270354 & 0.5305774 & 0.5361784 & 0.5406808 &
0.546150 & 0.5515398 & 0.5565069 & 0.5617383 & 0.5673462 & 0.5732439 &
0.5780718 & 0.5841174 & 0.5900685 & 0.5964953 & 0.603421 & 0.6107617 &
0.6156242 & 0.6220089 & 0.6293447 & 0.6343844 & 0.6424599 & 0.6500421 &
0.6581394 & 0.6632408 & 0.6684766 & 0.6763995 & 0.6843949 & 0.6915283 &
0.6997512 & 0.7080656 & 0.7169991\tabularnewline
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# identify break}
\KeywordTok{which}\NormalTok{(res.mat[}\DecValTok{1}\NormalTok{,] }\OperatorTok{>}\StringTok{ }\NormalTok{res.mat[}\DecValTok{2}\NormalTok{,])}\CommentTok{# break occured after 13}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
## [26] 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{id.comb <-}\StringTok{ }\KeywordTok{min}\NormalTok{(}\KeywordTok{which}\NormalTok{(res.mat[}\DecValTok{1}\NormalTok{,] }\OperatorTok{>}\StringTok{ }\NormalTok{res.mat[}\DecValTok{2}\NormalTok{,])) }\OperatorTok{-}\StringTok{ }\DecValTok{1} \CommentTok{#3}
\NormalTok{id.comb}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 13
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# calculate B}
\NormalTok{B <-}\StringTok{ }\KeywordTok{min}\NormalTok{(T.vec) }\CommentTok{#0.01955164}
\CommentTok{# solution with m - integers #######################}
\NormalTok{m.vec.int <-}\StringTok{ }\KeywordTok{round}\NormalTok{(T.vec}\OperatorTok{/}\NormalTok{B,}\DecValTok{0}\NormalTok{)}
\CommentTok{#I need to address this}
\NormalTok{m.vec.int[}\DecValTok{1}\OperatorTok{:}\NormalTok{id.comb] <-}\StringTok{ }\DecValTok{1}  
\CommentTok{# re-optimize B for fixed m.vec}
\NormalTok{B.int <-}\StringTok{ }\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{sum}\NormalTok{(c.or}\OperatorTok{/}\NormalTok{m.vec.int)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(m.vec.int}\OperatorTok{*}\NormalTok{H.vec))}\CommentTok{#0.02014868}
\CommentTok{# total cost }
\NormalTok{c.cost.int <-}\StringTok{ }\KeywordTok{jrp.obj.fun}\NormalTok{( }\DataTypeTok{m =}\NormalTok{ m.vec.int, }\DataTypeTok{B=}\NormalTok{B.int, }\DataTypeTok{cor =}\NormalTok{ c.or,}\DataTypeTok{Hvec=}\NormalTok{H.vec, }\DataTypeTok{cor0 =}\NormalTok{ c.or0)}\CommentTok{#192606}
\NormalTok{df <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{rbind}\NormalTok{(}\KeywordTok{round}\NormalTok{(T.vec}\OperatorTok{/}\NormalTok{B,}\DecValTok{2}\NormalTok{), }\KeywordTok{round}\NormalTok{(T.vec}\OperatorTok{/}\NormalTok{B), m.vec.int))}
\KeywordTok{colnames}\NormalTok{(df) <-}\StringTok{ }\NormalTok{reo.id }
\KeywordTok{rownames}\NormalTok{(df) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"$m_i=}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{frac\{T_i\}\{B\}$"}\NormalTok{ ,}\StringTok{"$[m_i]$"}\NormalTok{, }\StringTok{"$[}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{tilde\{m\}_i]$"}\NormalTok{ )}
\KeywordTok{kable}\NormalTok{(df,}\StringTok{"pandoc"}\NormalTok{, }\DataTypeTok{row.names =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr@{}}
\toprule
& 2 & 10 & 7 & 15 & 9 & 41 & 58 & 19 & 20 & 3 & 4 & 57 & 59 & 14 & 5 & 1
& 33 & 61 & 13 & 29 & 18 & 50 & 34 & 21 & 55 & 60 & 23 & 52 & 38 & 37 &
25 & 39 & 51 & 32 & 8 & 28 & 46 & 62 & 40 & 24 & 16 & 11 & 17 & 22 & 27
& 35 & 43 & 54 & 12 & 44 & 49 & 30 & 36 & 31 & 56 & 53 & 48 & 45 & 6 &
47 & 42 & 26\tabularnewline
\midrule
\endhead
\(m_i=\frac{T_i}{B}\) & 1 & 1.26 & 1.26 & 1.85 & 1.9 & 1.98 & 2.21 &
2.24 & 2.38 & 2.47 & 2.47 & 2.78 & 2.91 & 2.99 & 3.01 & 3.04 & 3.07 &
3.11 & 3.12 & 3.47 & 3.54 & 3.57 & 3.59 & 3.66 & 3.68 & 3.78 & 3.86 &
3.99 & 4.08 & 4.1 & 4.35 & 4.38 & 4.4 & 4.41 & 4.43 & 4.45 & 4.6 & 4.61
& 4.62 & 4.67 & 4.86 & 4.93 & 5.03 & 5.03 & 5.37 & 5.8 & 6.83 & 6.83 & 7
& 7.03 & 7.48 & 7.58 & 7.69 & 7.81 & 8.01 & 8.56 & 8.84 & 9.17 & 10.15 &
10.23 & 10.78 & 11.24\tabularnewline
\([m_i]\) & 1 & 1.00 & 1.00 & 2.00 & 2.0 & 2.00 & 2.00 & 2.00 & 2.00 &
2.00 & 2.00 & 3.00 & 3.00 & 3.00 & 3.00 & 3.00 & 3.00 & 3.00 & 3.00 &
3.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 &
4.0 & 4.00 & 4.00 & 4.0 & 4.00 & 4.00 & 4.00 & 5.0 & 5.00 & 5.00 & 5.00
& 5.00 & 5.00 & 5.00 & 5.00 & 5.00 & 6.0 & 7.00 & 7.00 & 7 & 7.00 & 7.00
& 8.00 & 8.00 & 8.00 & 8.00 & 9.00 & 9.00 & 9.00 & 10.00 & 10.00 & 11.00
& 11.00\tabularnewline
\([\tilde{m}_i]\) & 1 & 1.00 & 1.00 & 1.00 & 1.0 & 1.00 & 1.00 & 1.00 &
1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 3.00 & 3.00 & 3.00 & 3.00 & 3.00 &
3.00 & 3.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 &
4.00 & 4.0 & 4.00 & 4.00 & 4.0 & 4.00 & 4.00 & 4.00 & 5.0 & 5.00 & 5.00
& 5.00 & 5.00 & 5.00 & 5.00 & 5.00 & 5.00 & 6.0 & 7.00 & 7.00 & 7 & 7.00
& 7.00 & 8.00 & 8.00 & 8.00 & 8.00 & 9.00 & 9.00 & 9.00 & 10.00 & 10.00
& 11.00 & 11.00\tabularnewline
\bottomrule
\end{longtable}

Reoptimizing basic cycle time yields \(B=\) \(0.29\) and the total cost
are \ensuremath{1.579347\times 10^{4}}

The order quantities are given by multiplying the cycle times \(T_i\)
with demand rates \(y_i\), i.e.~\(q_i = T_i \cdot y_i\) such that

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dei <-}\StringTok{ }\NormalTok{dei[reo.id]}
\NormalTok{df <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{rbind}\NormalTok{( m.vec.int, }\KeywordTok{round}\NormalTok{(m.vec.int}\OperatorTok{*}\NormalTok{B, }\DecValTok{2}\NormalTok{), }\KeywordTok{round}\NormalTok{(m.vec.int}\OperatorTok{*}\NormalTok{B}\OperatorTok{*}\NormalTok{dei, }\DecValTok{2}\NormalTok{) ))}
\KeywordTok{colnames}\NormalTok{(df) <-}\StringTok{ }\NormalTok{reo.id }
\KeywordTok{rownames}\NormalTok{(df) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"$[}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{tilde\{m\}_i]$"}\NormalTok{, }\StringTok{"$T_i$"}\NormalTok{, }\StringTok{"$q_i$"}\NormalTok{ )}
\KeywordTok{kable}\NormalTok{(df,}\StringTok{"pandoc"}\NormalTok{, }\DataTypeTok{row.names =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr@{}}
\toprule
& 2 & 10 & 7 & 15 & 9 & 41 & 58 & 19 & 20 & 3 & 4 & 57 & 59 & 14 & 5 & 1
& 33 & 61 & 13 & 29 & 18 & 50 & 34 & 21 & 55 & 60 & 23 & 52 & 38 & 37 &
25 & 39 & 51 & 32 & 8 & 28 & 46 & 62 & 40 & 24 & 16 & 11 & 17 & 22 & 27
& 35 & 43 & 54 & 12 & 44 & 49 & 30 & 36 & 31 & 56 & 53 & 48 & 45 & 6 &
47 & 42 & 26\tabularnewline
\midrule
\endhead
\([\tilde{m}_i]\) & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 &
1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 3.00 & 3.00 & 3.00 & 3.00 &
3.00 & 3.00 & 3.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 &
4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 4.00 & 5.00 &
5.00 & 5.00 & 5.00 & 5.00 & 5.00 & 5.00 & 5.00 & 5.00 & 6.00 & 7.00 &
7.00 & 7.00 & 7.00 & 7.00 & 8.00 & 8.00 & 8.00 & 8.00 & 9.00 & 9.00 &
9.00 & 10.00 & 10.00 & 11.00 & 11.00\tabularnewline
\(T_i\) & 0.23 & 0.23 & 0.23 & 0.23 & 0.23 & 0.23 & 0.23 & 0.23 & 0.23 &
0.23 & 0.23 & 0.23 & 0.23 & 0.69 & 0.69 & 0.69 & 0.69 & 0.69 & 0.69 &
0.69 & 0.92 & 0.92 & 0.92 & 0.92 & 0.92 & 0.92 & 0.92 & 0.92 & 0.92 &
0.92 & 0.92 & 0.92 & 0.92 & 0.92 & 0.92 & 0.92 & 1.15 & 1.15 & 1.15 &
1.15 & 1.15 & 1.15 & 1.15 & 1.15 & 1.15 & 1.38 & 1.62 & 1.62 & 1.62 &
1.62 & 1.62 & 1.85 & 1.85 & 1.85 & 1.85 & 2.08 & 2.08 & 2.08 & 2.31 &
2.31 & 2.54 & 2.54\tabularnewline
\(q_i\) & 340.20 & 181.41 & 139.63 & 302.35 & 60.47 & 226.88 & 120.94 &
120.94 & 56.78 & 72.70 & 72.70 & 50.55 & 226.88 & 453.52 & 389.13 &
302.58 & 181.41 & 1088.45 & 181.41 & 227.11 & 907.50 & 454.21 & 604.69 &
1209.39 & 454.21 & 202.18 & 241.88 & 241.88 & 483.76 & 483.76 & 604.69 &
660.09 & 161.56 & 227.11 & 558.53 & 120.94 & 504.30 & 1814.08 & 504.30 &
755.87 & 604.69 & 907.04 & 567.77 & 567.77 & 201.95 & 181.41 & 127.63 &
85.63 & 127.63 & 195.49 & 85.63 & 193.87 & 129.25 & 193.87 & 145.87 &
164.10 & 164.10 & 251.34 & 182.33 & 228.49 & 251.34 &
444.29\tabularnewline
\bottomrule
\end{longtable}

--\textgreater{} Now the question is: Is this feasible? --\textgreater{}
no:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{q.vec <-}\StringTok{ }\NormalTok{m.vec.int}\OperatorTok{*}\NormalTok{B}\OperatorTok{*}\NormalTok{dei}
\KeywordTok{const.fun}\NormalTok{(q.vec) }\OperatorTok{>}\StringTok{ }\NormalTok{rack_total_width}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\hypertarget{including-capacity-constraint}{%
\subsection{Including capacity
constraint}\label{including-capacity-constraint}}

When you try to optimize the JRP directly, without introducing the
substitution \(T_i = m_i \cdot B\) you need to update the JRP function
as follows

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ROI)}
\NormalTok{jrp.obj.fun2 <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(Tvec, cor, Hvec, cor0) }\KeywordTok{sum}\NormalTok{(cor0}\OperatorTok{/}\NormalTok{Tvec) }\OperatorTok{+}\StringTok{ }\KeywordTok{sum}\NormalTok{(cor}\OperatorTok{/}\NormalTok{Tvec) }\OperatorTok{+}\StringTok{ }\KeywordTok{sum}\NormalTok{(Hvec}\OperatorTok{*}\NormalTok{Tvec)}
\CommentTok{# you need to initialize the parameters in the objective function --> Tvec is to be optimized over, the rest is given}
\NormalTok{jrp.obj.fun2 <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(Tvec, }\DataTypeTok{cor=}\NormalTok{c.or, }\DataTypeTok{Hvec =}\NormalTok{ H.vec, }\DataTypeTok{cor0 =}\NormalTok{ c.or0) }\KeywordTok{sum}\NormalTok{(cor0}\OperatorTok{/}\NormalTok{Tvec) }\OperatorTok{+}\StringTok{ }\KeywordTok{sum}\NormalTok{(cor}\OperatorTok{/}\NormalTok{Tvec) }\OperatorTok{+}\StringTok{ }\KeywordTok{sum}\NormalTok{(Hvec}\OperatorTok{*}\NormalTok{Tvec)}

\NormalTok{qopt2 <-}\StringTok{ }\KeywordTok{OP}\NormalTok{(}
  \DataTypeTok{objective =} \KeywordTok{F_objective}\NormalTok{(}\DataTypeTok{F=}\NormalTok{jrp.obj.fun2 , }\DataTypeTok{n=}\DecValTok{62}\NormalTok{),}
  \DataTypeTok{types =} \KeywordTok{rep}\NormalTok{(}\StringTok{"C"}\NormalTok{,n),}
  \DataTypeTok{bounds =} \KeywordTok{V_bound}\NormalTok{(}\DataTypeTok{ub=} \KeywordTok{rep}\NormalTok{(}\DecValTok{30}\NormalTok{, }\DecValTok{62}\NormalTok{), }\DataTypeTok{lb=} \KeywordTok{rep}\NormalTok{(.}\DecValTok{001}\NormalTok{,}\DecValTok{62}\NormalTok{))}
\NormalTok{) }

\KeywordTok{jrp.obj.fun2}\NormalTok{(m.vec.int}\OperatorTok{*}\NormalTok{B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 161795.8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{jrp.obj.fun2}\NormalTok{(}\KeywordTok{rep}\NormalTok{(.}\DecValTok{00001}\NormalTok{,}\DecValTok{62}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9724500000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{jrp.obj.fun2}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{15}\NormalTok{,}\DecValTok{62}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 126671.4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# you don't need Alabama here as there is no constraint. Basically you can also optimize this problem by taking derivatives}
\NormalTok{copt_sol2 <-}\StringTok{ }\KeywordTok{ROI_solve}\NormalTok{(qopt2, }\DataTypeTok{start =}\NormalTok{ m.vec.int}\OperatorTok{*}\NormalTok{B)}
\NormalTok{copt_sol2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Optimal solution found.
## The objective value is: 4.805155e+04
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{copt_sol2}\OperatorTok{$}\NormalTok{solution}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1]  1.285034  1.423363  1.430040  1.900573  2.156868  2.098047  2.837086
##  [8]  2.296972  2.440465  3.342526  3.342515  3.572972  3.738811  3.068450
## [15]  3.548053  3.908338  3.150675  3.402864  3.532098  3.564189  3.635661
## [22]  4.589049  3.685419  3.749288  4.730247  4.852348  3.962893  5.127727
## [29]  4.317404  4.337637  4.461237  4.627858  5.652664  4.525522  5.018690
## [36]  4.559422  4.867844  5.044310  4.882314  4.793101  4.981655  5.577597
## [43]  5.156001  5.156000  5.505243  5.948902  7.224267  8.778482  7.930251
## [50]  7.437641  9.612507  7.773793  8.137857  8.006261 10.298182 11.004931
## [57]  9.350949  9.696093 11.491834 10.815501 11.400510 11.526746
\end{verbatim}

--\textgreater{} You should integrate the shelf capacity constraint
--\textgreater{} I also recommmend to stick with the basic period
approach

This is formally defined as
\[ \sum_{i=1}^n b_i \cdot \left\lceil\frac{b^{-1}_i \cdot q_i}{rl} \right \rceil \leq \text{tot_rack_length}\]
Thus, with the substitution above, the left-hand side changes to
\[ \sum_{i=1}^n b_i \cdot \left\lceil\frac{b^{-1}_i \cdot T_i \cdot y_i}{rl} \right \rceil = \sum_{i=1}^n b_i \cdot \left\lceil\frac{b^{-1}_i \cdot m_i \cdot B \cdot y_i}{rl} \right \rceil\]

Thus, you can change the constraint function quite easily

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{const.fun2 <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(m, }\DataTypeTok{B =}\NormalTok{ B.start, }\DataTypeTok{y=}\NormalTok{ dei, }\DataTypeTok{bns =}\NormalTok{ product_data}\OperatorTok{$}\NormalTok{b_not_sorting, }\DataTypeTok{bs =}\NormalTok{ product_data}\OperatorTok{$}\NormalTok{b_sorting, }\DataTypeTok{rl =}\NormalTok{ rack_length) \{}
  \KeywordTok{sum}\NormalTok{(bs }\OperatorTok{*}\StringTok{ }\KeywordTok{ceiling}\NormalTok{( bns }\OperatorTok{*}\StringTok{ }\NormalTok{m}\OperatorTok{*}\NormalTok{B}\OperatorTok{*}\NormalTok{y }\OperatorTok{/}\StringTok{ }\NormalTok{rl))}
\NormalTok{  \}}
\end{Highlighting}
\end{Shaded}

Then, you can use the original JRP function and update the model by
including the capacity constraint. Therefore I recommend that you fix
\(B\) to some appropriate value based on the feasible solution above

\(rack_{Totalwidth}=51200\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rack_total_width<-}\DecValTok{51200}
\CommentTok{# we reinitialize the vectors}
\NormalTok{n <-}\StringTok{ }\KeywordTok{length}\NormalTok{(product_data}\OperatorTok{$}\StringTok{`}\DataTypeTok{box ID}\StringTok{`}\NormalTok{)}
\NormalTok{c.or0 <-}\StringTok{ }\NormalTok{cord}
\NormalTok{c.or <-}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\NormalTok{ordering_cost}
\NormalTok{H.vec <-}\StringTok{ }\FloatTok{0.1} \OperatorTok{*}\StringTok{ }\NormalTok{product_data}\OperatorTok{$}\NormalTok{box_cost }\OperatorTok{*}\StringTok{ }\NormalTok{dei }\OperatorTok{*}\StringTok{ }\FloatTok{.05}


\NormalTok{T.feas <-}\StringTok{ }\NormalTok{copt_sol}\OperatorTok{$}\NormalTok{solution}\OperatorTok{/}\NormalTok{dei}
\NormalTok{B.start <-}\StringTok{ }\KeywordTok{min}\NormalTok{(T.feas)}

\NormalTok{jrp.obj.fun <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(m , }\DataTypeTok{B =}\NormalTok{ B.start, }\DataTypeTok{cor =}\NormalTok{ c.or, }\DataTypeTok{Hvec =}\NormalTok{ H.vec, }\DataTypeTok{cor0 =}\NormalTok{ c.or0) cor0}\OperatorTok{/}\NormalTok{B }\OperatorTok{+}\StringTok{ }\KeywordTok{sum}\NormalTok{(cor}\OperatorTok{/}\NormalTok{B}\OperatorTok{/}\NormalTok{m) }\OperatorTok{+}\StringTok{ }\KeywordTok{sum}\NormalTok{(Hvec}\OperatorTok{*}\NormalTok{B}\OperatorTok{*}\NormalTok{m)}
\KeywordTok{jrp.obj.fun}\NormalTok{(}\DataTypeTok{m=} \KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{62}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 541114.9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{const.fun2}\NormalTok{(}\DataTypeTok{m=} \KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{62}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 30116
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{qopt3 <-}\StringTok{ }\KeywordTok{OP}\NormalTok{(}
  \DataTypeTok{objective =} \KeywordTok{F_objective}\NormalTok{(}\DataTypeTok{F=}\NormalTok{jrp.obj.fun ,}\DataTypeTok{n=}\NormalTok{n),}
  \CommentTok{# now integer decision variables}
  \DataTypeTok{types =} \KeywordTok{rep}\NormalTok{(}\StringTok{"C"}\NormalTok{,n),}
  \DataTypeTok{bounds =} \KeywordTok{V_bound}\NormalTok{(}\DataTypeTok{li =} \DecValTok{1}\OperatorTok{:}\NormalTok{n, }\DataTypeTok{ui =} \DecValTok{1}\OperatorTok{:}\NormalTok{n, }\DataTypeTok{ub=} \KeywordTok{rep}\NormalTok{(}\DecValTok{50}\NormalTok{, n) , }\DataTypeTok{lb=} \KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{, n)),}
  \DataTypeTok{constraints =} \KeywordTok{F_constraint}\NormalTok{(}\DataTypeTok{F=}\NormalTok{const.fun2,}
                             \DataTypeTok{dir=}\StringTok{"<="}\NormalTok{,}
                             \DataTypeTok{rhs =}\NormalTok{ rack_total_width)}
\NormalTok{)}
\CommentTok{# god starting point essential --> m = T.feas/B.start}
\NormalTok{copt_sol3 <-}\StringTok{ }\KeywordTok{ROI_solve}\NormalTok{(qopt3, }\DataTypeTok{start =}\NormalTok{ T.feas}\OperatorTok{/}\NormalTok{B.start , }\DataTypeTok{solver =} \StringTok{"alabama"}\NormalTok{)}

\NormalTok{copt_sol3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## No optimal solution found.
## The solver message was: Convergence due to lack of progress in parameter updates.
## The objective value is: 2.398360e+05
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{copt_sol3}\OperatorTok{$}\NormalTok{solution}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1]  1.434978  2.155794  3.143564  1.451799  8.171966  1.763152  3.841270
##  [8]  4.059278  7.822788  5.969841  6.499541  7.773522  1.984330  2.997725
## [15]  2.972406  4.807334  8.168963  1.000000  8.087969  6.140702  1.579545
## [22]  4.350131  3.180915  1.506091  4.003943  8.995795  7.350288  7.041377
## [29]  4.022780  3.517363  2.817248  2.857323 11.853796  8.046825  3.118729
## [36] 13.001013  4.902905  1.363331  4.511474  3.294681  3.281027  2.327095
## [43]  3.507784  3.794970 10.755039 16.472815 23.124729 33.071314 19.844618
## [50] 17.929875 34.912128 18.448320 23.930581 14.796675 27.474786 21.144562
## [57] 23.500268 17.449419 24.918863 19.217123 16.506069  9.514601
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{jrp.obj.fun}\NormalTok{(}\DataTypeTok{m=}\NormalTok{ copt_sol3}\OperatorTok{$}\NormalTok{solution)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 239836
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{const.fun2}\NormalTok{(}\DataTypeTok{m=}\NormalTok{ copt_sol3}\OperatorTok{$}\NormalTok{solution) }\OperatorTok{<=}\StringTok{ }\NormalTok{rack_total_width}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# not feasible}
\KeywordTok{const.fun2}\NormalTok{(}\KeywordTok{round}\NormalTok{(copt_sol3}\OperatorTok{$}\NormalTok{solution)) }\OperatorTok{<=}\StringTok{ }\NormalTok{rack_total_width}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# feasible}
\KeywordTok{const.fun2}\NormalTok{(}\KeywordTok{floor}\NormalTok{(copt_sol3}\OperatorTok{$}\NormalTok{solution)) }\OperatorTok{<=}\StringTok{ }\NormalTok{rack_total_width}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# potential starting solution}
\NormalTok{m.start <-}\StringTok{ }\KeywordTok{floor}\NormalTok{(copt_sol3}\OperatorTok{$}\NormalTok{solution) }\CommentTok{# multiplier m}
\NormalTok{q.start <-}\StringTok{ }\KeywordTok{ceiling}\NormalTok{(m.start }\OperatorTok{*}\StringTok{ }\NormalTok{B.start }\OperatorTok{*}\StringTok{ }\NormalTok{dei)   }\CommentTok{# order quantity q (in boxes, rounded up)}
\end{Highlighting}
\end{Shaded}

Afterwards, you have to find a layout scheme such that a precise shelf
layout results.

As you rightly point out you need to calculate the number of lanes
\(l(q_i)\) required for each product given a certain order quantity
\(q_i\) (integer number of boxes):

\[l(q_i) =\left\lceil \frac{q_i}{n_i} \right\rceil\] whereby \(n_i\) is
the number of boxes per lane dedicated to product \(i\). I.e.,
\[n_i = \left\lfloor \frac{rl}{b_i^{-1}} \right\rfloor\]. Thus, for the
solution of the JRP we have:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{l.start <-}\StringTok{ }\KeywordTok{ceiling}\NormalTok{(q.start}\OperatorTok{/}\KeywordTok{floor}\NormalTok{(rack_length}\OperatorTok{/}\NormalTok{product_data}\OperatorTok{$}\NormalTok{b_not_sorting))}
\NormalTok{l.start}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 1 1 1 1 2 2 3 4 3 3 3 3 2 1 1 2 2 2 2 2 1 2 2 1 2 2 2 2 2 2 1 2 2 2 2 1 1 1
## [39] 1 2 1 1 1 1 1 2 1 1 1 2 1 2 1 1 2 1 1 2 2 1 2 2
\end{verbatim}

Now, these lanes have to be assigned to the levels of the shelves.
Therefore, we first need to determine the types of lanes required. The
lanes are just described by their width. Due to the safety margins we
should round the lane width to full centimeter. I.e., we need to assign
lanes with the following widths

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{unique}\NormalTok{(}\KeywordTok{round}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{b_sorting}\OperatorTok{/}\DecValTok{100}\NormalTok{)}\OperatorTok{*}\DecValTok{100}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 200 400 600
\end{verbatim}

Now comes the tricky part: We have to decide how many lanes of a certain
width should be assigned for each level. Luckily, there is only a small
number of useful patterns of lanes per level. To be precise there are 9
efficient patterns to arrange these 3 lane types (assuming we use each
level exhaustively):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{patterns <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}
\KeywordTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{),}
\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{0}\NormalTok{),}
\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}
\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{),}
\KeywordTok{c}\NormalTok{(}\DecValTok{6}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{),}
\KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{0}\NormalTok{),}
\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{0}\NormalTok{),}
\KeywordTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{),}
\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{)}
\NormalTok{)}
\KeywordTok{colnames}\NormalTok{(patterns) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"200"}\NormalTok{,}\StringTok{"400"}\NormalTok{,}\StringTok{"600"}\NormalTok{)}

\NormalTok{patterns}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       200 400 600
##  [1,]   8   0   0
##  [2,]   0   4   0
##  [3,]   0   1   2
##  [4,]   2   0   2
##  [5,]   6   1   0
##  [6,]   4   2   0
##  [7,]   2   3   0
##  [8,]   3   1   1
##  [9,]   1   2   1
\end{verbatim}

Let \(p_{k,j}\) indicate the number of lanes of type \(j\) associated to
pattern \(k\). Now we need to assess the number of lanes per required of
each type. As outlined above, we know the number of lanes per product
\(l(q_i)\), thus we can deduce the demand for lane type \(j\) (\(ld_j\))
by summing up the \(l(q_i)\) for each lane type, i.e.,
\(ld_j = \sum_{i \in P|b_i=j} l(q_i)\):

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# assign lane width as names}
\KeywordTok{names}\NormalTok{(l.start) <-}\StringTok{ }\KeywordTok{round}\NormalTok{(product_data}\OperatorTok{$}\NormalTok{b_sorting}\OperatorTok{/}\DecValTok{100}\NormalTok{)}\OperatorTok{*}\DecValTok{100} 

\CommentTok{# number of items with lane types 200, 400, 600 that is demand for each lane type}
\NormalTok{ld <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\KeywordTok{sum}\NormalTok{(l.start[}\KeywordTok{names}\NormalTok{(l.start) }\OperatorTok{==}\StringTok{ "200"}\NormalTok{]),}
\KeywordTok{sum}\NormalTok{(l.start[}\KeywordTok{names}\NormalTok{(l.start) }\OperatorTok{==}\StringTok{ "400"}\NormalTok{]),}
\KeywordTok{sum}\NormalTok{(l.start[}\KeywordTok{names}\NormalTok{(l.start) }\OperatorTok{==}\StringTok{ "600"}\NormalTok{]))}
\NormalTok{ld}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19 17 68
\end{verbatim}

\hypertarget{changes-made-on-q}{%
\subsection{Changes made on q}\label{changes-made-on-q}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  We assumed that there are 262 working days for the year 2020 according
  to
  \url{https://hr.uiowa.edu/pay/payroll-services/payroll-calendars/working-day-payroll-calendar-2020}
\item
  rack\_total\_width which was 56,000 mm, looking at the 9 patterns all
  of which have 150 mm in waste, meaning all 32 levels will have 150 mm
  waste each. Therefor \(56,000 - (150 *32) = 51,200\) thereby changing
  rack total width 51,200.
\item
  These changes then affects the values of q for all the 62 items
  involved.
\end{enumerate}

To fulfill lane demands from the items \(ld\) are 15 lanes with with
200, 15 lanes with width 400 and 64 lanes with width 600. To fulfull
this demand, only 2 patterns are needed.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{patterns[}\DecValTok{3}\OperatorTok{:}\DecValTok{4}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      200 400 600
## [1,]   0   1   2
## [2,]   2   0   2
\end{verbatim}

Assign Patterns

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fitted.pattern <-}\StringTok{ }\NormalTok{patterns[}\DecValTok{3}\OperatorTok{:}\DecValTok{4}\NormalTok{,]}
\CommentTok{# loop through 32 levels to assign patterns}

\NormalTok{levels.pattern.mat <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\DecValTok{0}\NormalTok{,  }\DataTypeTok{nrow =} \DecValTok{32}\NormalTok{,}\DataTypeTok{ncol =} \DecValTok{3}\NormalTok{)}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\DecValTok{32}\NormalTok{) \{}
  \ControlFlowTok{for}\NormalTok{ (j }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{) \{}
    
  \ControlFlowTok{if}\NormalTok{(i}\OperatorTok{<=}\StringTok{ }\DecValTok{16}\NormalTok{)\{}
\NormalTok{    levels.pattern.mat[i,j] <-}\StringTok{ }\KeywordTok{t}\NormalTok{(fitted.pattern[}\DecValTok{1}\NormalTok{,j])}
\NormalTok{  \} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{     levels.pattern.mat[i,j] <-}\StringTok{ }\KeywordTok{t}\NormalTok{(fitted.pattern[}\DecValTok{2}\NormalTok{,j])}
\NormalTok{   \}}
\NormalTok{  \}}
\NormalTok{\}}


\NormalTok{levels.pattern.mat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       [,1] [,2] [,3]
##  [1,]    0    1    2
##  [2,]    0    1    2
##  [3,]    0    1    2
##  [4,]    0    1    2
##  [5,]    0    1    2
##  [6,]    0    1    2
##  [7,]    0    1    2
##  [8,]    0    1    2
##  [9,]    0    1    2
## [10,]    0    1    2
## [11,]    0    1    2
## [12,]    0    1    2
## [13,]    0    1    2
## [14,]    0    1    2
## [15,]    0    1    2
## [16,]    0    1    2
## [17,]    2    0    2
## [18,]    2    0    2
## [19,]    2    0    2
## [20,]    2    0    2
## [21,]    2    0    2
## [22,]    2    0    2
## [23,]    2    0    2
## [24,]    2    0    2
## [25,]    2    0    2
## [26,]    2    0    2
## [27,]    2    0    2
## [28,]    2    0    2
## [29,]    2    0    2
## [30,]    2    0    2
## [31,]    2    0    2
## [32,]    2    0    2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# confirm if lane demand is met.}

\KeywordTok{sum}\NormalTok{(levels.pattern.mat[}\DecValTok{1}\OperatorTok{:}\DecValTok{32}\NormalTok{,}\DecValTok{1}\NormalTok{]) }\OperatorTok{>=}\StringTok{ }\KeywordTok{sum}\NormalTok{(ld[}\DecValTok{1}\NormalTok{]) }\CommentTok{#TRUE  for 200}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(levels.pattern.mat[}\DecValTok{1}\OperatorTok{:}\DecValTok{32}\NormalTok{,}\DecValTok{2}\NormalTok{]) }\OperatorTok{>=}\StringTok{ }\KeywordTok{sum}\NormalTok{(ld[}\DecValTok{2}\NormalTok{]) }\CommentTok{#TRUE  for 400}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(levels.pattern.mat[}\DecValTok{1}\OperatorTok{:}\DecValTok{32}\NormalTok{,}\DecValTok{3}\NormalTok{]) }\OperatorTok{>=}\StringTok{ }\KeywordTok{sum}\NormalTok{(ld[}\DecValTok{3}\NormalTok{]) }\CommentTok{#TRUE  for 600}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE
\end{verbatim}

\end{document}
